services:
  configurator:
    environment:
      PROJECT_CLONE_URL: https://github.com/dockersamples/labspace-building-secure-images

  workspace:
    ports: !override # Don't expose port 3000
      - 8085:8085
